config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'locations/search' => 'locations#search'
  get 'locations/search/results' => 'locations#results'
  resources :locations, :nearbylocations, :markers
  get 'about' => 'about#index'
  resources :artists, :constraints => { :id => /.*/ }

end

app/models/location.rb
class Location < ActiveRecord::Base

reverse_geocoded_by :latitude, :longitude,
  :address => :address
after_validation :reverse_geocode

end

app/models/place.rb
class Place < ActiveRecord::Base

reverse_geocoded_by :latitude, :longitude,
  :address => :address
after_validation :reverse_geocode

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  def index
    @artists = Place.select(:artist).map(&:artist).uniq.sort_by(&:downcase)
    @artistcount = @artists.length/3
    @artists1 = @artists[0..(@artistcount-1)]
    @artists2 = @artists[(@artistcount)..(@artistcount*2-1)]
    @artists3 = @artists[(@artistcount*2)..(@artistcount*3-1)]
  end

  def show
    @artist = params[:id]
    @works = Place.where(artist:@artist)
    @name = @artist.split(",")
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Location.select(:artist).map(&:artist).uniq.sort_by(&:downcase)
  end

  def show
    @artist = params[:id]
    @works = Location.where(artist:@artist)
    @name = @artist.split(",").reverse.join(" ")
  end

end

app/controllers/artistsearch_controller.rb
class ArtistsearchController < ApplicationController
  def index
    @artists = Place.select(:artist).map(&:artist).uniq.sort_by(&:downcase)
    @artistcount = @artists.length/3
    @artists1 = @artists[0..(@artistcount-1)]
    @artists2 = @artists[(@artistcount)..(@artistcount*2-1)]
    @artists3 = @artists[(@artistcount*2)..(@artistcount*3-1)]
  end

  def show
    @artist = params[:id]
    @works = Place.where(artist:@artist)
    @name = @artist.split(",")
  end

end

app/controllers/farsearch_controller.rb
class FarsearchController < ApplicationController
  def index
  end

  def search
    @result = Place.near(params["query"], 10, :order => "distance").limit(10)
    @getresults = @result.length > 0
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
  end

  def search
  end

  def results
    @results = Location.near(params["query"], 10, :order => "distance").limit(10)
  end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController

  def index
    if request.xhr?
      render(json: Location.all)
    else
      redirect_to root_path
    end
  end

  def show
    if request.xhr?
      render(json: Location.find(params['markerid']))
    else
      redirect_to root_path
    end
  end


end

app/controllers/nearbylocations_controller.rb
class NearbylocationsController < ApplicationController
  def index
    if request.xhr?
      @nearbyspots = Location.near([params['lat'], params['long']], 10, :order => "distance").limit(100)
      render :json => {
        :nearbyspots => @nearbyspots
      }
    end
  end

end

app/controllers/shownearby_controller.rb
class ShownearbyController < ApplicationController
  def index
  end

  def load
    @resulttrack = 0
    @@resultspage = 0
    @showprev = false
    @shownext = true
    @@allspots = Place.near([params['lat'], params['long']], 10, :order => "distance").limit(100)
    @nearbyspots = Place.near([params['lat'], params['long']], 10, :order => "distance").limit(100)[@@resultspage..@@resultspage+9]
    render :json => {
      :partial => render_to_string(:partial => 'shownearby/map')
    }
  end

  def nextresults
    @@resultspage += 10
    @resulttrack = @@resultspage
    @showprev = @@resultspage > 0
    @shownext = @@resultspage < 90
    @nearbyspots = @@allspots[@@resultspage..@@resultspage+9]
    p @nearbyspots
    render :json => {
      :partial => render_to_string(:partial => 'shownearby/locations')
    }
  end

  def prevresults
    @@resultspage -= 10
    @resulttrack = @@resultspage
    @showprev = @@resultspage > 0
    @shownext = @@resultspage < 90
    @nearbyspots = @@allspots[@@resultspage..@@resultspage+9]
    p @nearbyspots
    render :json => {
      :partial => render_to_string(:partial => 'shownearby/locations')
    }
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artistsearch_helper.rb
module ArtistsearchHelper
end

app/helpers/locationsearch_helper.rb
module LocationsearchHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/nearbysearch_helper.rb
module NearbysearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<%= javascript_include_tag 'about/slider.js' %>
<%= javascript_include_tag 'about/pageinteractions.js' %>
<div id="slideshow">
  <%= image_tag("slide4.jpg") %>
  <%= image_tag("slide2.jpg") %>
  <%= image_tag("slide3.jpg") %>
  <%= image_tag("slide1.jpg") %>
</div>
<div id="abouttext">
  <p>
    SF Open Art is a spare time project that documents all open civic artwork in San Francisco with the help of the SF OpenData project. The website calls upon the SF OpenData database to find display locations, titles, and other significant details. All San Francisco maps are created through Google Maps with the aid of the Rails Geocoder gem.
  </p>
  <p>
    The project was conceived with the idea of highlighting San Francisco's public artwork through a simple interface. Both tourists and locals can use the website to explore the City's open treasures.
  </p>
</div>

app/views/artists/index.html.erb
<%= react_component('ArtistList', { artists: @artists }) %>

app/views/artists/show.html.erb
<%= javascript_include_tag 'artists/artistsearchscript.js' %>

<div id = "artistmap"></div>
<div id = "artistresults">
  <%= react_component('ArtistPage', { works: @works, artist: @name }) %>
</div>

app/views/farsearch/index.html.erb
<%= form_tag("/farsearch/search", method: "get") do %>
  <%= label_tag("Please enter a search for an address or location (ie: Pier 39; 100 Market Street, San Francisco; Golden Gate Park)") %>
  <br>
  <br>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/farsearch/search.html.erb
<%= javascript_include_tag 'farsearch/loadresults.js'%>

<div id= "resultmap"></div>
<div id= "results">
<%if @getresults%>
  <%@result.each do |item|%>
  <p>
    <%=link_to item.title, item.title, class: "result", data: {latitude: item.latitude, longitude: item.longitude, address: item.address} %>
    <br>
    <%=item.artist%> (<%=link_to 'search', artistsearch_path(item.artist)%>)
  </p>
  <%end%>
<%else%>
  <p>
    Your search request returns no results. Please try another location.
  </p>
<%end%>
</div>

app/views/locations/index.html.erb
<%= javascript_include_tag 'locations/mapinteractivity.js' %>

<div id="fullmap">
</div>
<div id="fullmapdesc">
  <h5>Click on a marker to pull up information on it.</h5>
</div>

app/views/locations/results.html.erb
<%= javascript_include_tag 'locations/searchresultmapinteractivity.js' %>
<div id= "resultmap"></div>
<div id= "results">
  <%= react_component("LocationSearches", {results:@results}) %>
</div>

app/views/locations/search.html.erb
<%= form_tag(locations_search_results_path, method: "get") do %>
  <%= label_tag("Please enter a search for an address or location (ie: Pier 39; 100 Market Street, San Francisco; Golden Gate Park)") %>
  <br>
  <br>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<div id='app'></div>

app/views/nearbylocations/index.html.erb
<%= javascript_include_tag 'nearbylocations/mapinteractivity.js' %>
<div id = "nearmap"></div>
<div id = "locationframe">
  <%= react_component("ResultListContainer") %>
</div>

app/views/nearbysearch/_locations.html.erb
<div id = "locations">
  <% @nearbyspots.each_with_index do |place, index| %>
  <p class = "nearbylocation">
    <%= @resultindex + index %>. Piece Title: <%= place.title%>
    <br>
    Artist: <%= place.artist%> (<%=link_to "Search", artistsearch_path(place.artist) %>)
    <br>
    <%=link_to place.address, root_path, data: {lat: place.latitude, long: place.longitude}, class: "address" %>
  </p>
  <%end%>
  <%if @showprev %>
    <%=link_to "previous", nearbysearch_path(@resultindex - 10), class: "results"%>
  <%end%>
  <%if @shownext %>
    <%=link_to "next", nearbysearch_path(@resultindex + 10), class: "results"%>
  <%end%>
</div>

app/views/nearbysearch/_map.html.erb
<%= javascript_include_tag 'nearbysearch/pageinteractions.js'%>
<div id = "nearmap"></div>
<div id = "locationframe">
  <%=render partial: "locations"%>
</div>
<div id = "mapdesc">'A' represents your current location, and 'B' represents your requested destination. </div>

app/views/shownearby/_map.html.erb
<%= javascript_include_tag 'shownearby/createmap.js'%>
<div id = "nearmap"></div>
<div id = "locationframe">
<%=render partial: "locations"%>
</div>
<div id = "mapdesc">'A' represents your current location, and 'B' represents your requested destination. </div>

app/views/shownearby/index.html.erb
  <%= javascript_include_tag 'shownearby/shownearbyload.js'%>

<div id = "content">Now loading... please make sure you are sharing your current location</div>

app/views/welcome/index.html.erb
<div class="wrapper">
  <div id="indexbox">
  <h1>Welcome to SF Open Art!</h1>
  <h3>SF Open Art is a whole new way to discover San Francisco's outdoor civic artwork. </h3>
  <br>
  <h3>Start exploring and searching for art with the tools above.</h3>
  </div>
</div>