config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'locations/search' => 'locations#search'
  get 'locations/search/results' => 'locations#results'
  resources :locations, :nearbylocations, :markers
  get 'about' => 'about#index'
  resources :artists, :constraints => { :id => /.*/ }

end

app/models/location.rb
class Location < ActiveRecord::Base

reverse_geocoded_by :latitude, :longitude,
  :address => :address
after_validation :reverse_geocode

end

app/models/place.rb
class Place < ActiveRecord::Base

reverse_geocoded_by :latitude, :longitude,
  :address => :address
after_validation :reverse_geocode

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  def index
    @artists = Place.select(:artist).map(&:artist).uniq.sort_by(&:downcase)
    @artistcount = @artists.length/3
    @artists1 = @artists[0..(@artistcount-1)]
    @artists2 = @artists[(@artistcount)..(@artistcount*2-1)]
    @artists3 = @artists[(@artistcount*2)..(@artistcount*3-1)]
  end

  def show
    @artist = params[:id]
    @works = Place.where(artist:@artist)
    @name = @artist.split(",")
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Location.select(:artist).map(&:artist).uniq.sort_by(&:downcase)
  end

  def show
    @artist = params[:id]
    @works = Location.where(artist:@artist)
    @name = @artist.split(",").reverse.join(" ")
  end

end

app/controllers/artistsearch_controller.rb
class ArtistsearchController < ApplicationController
  def index
    @artists = Place.select(:artist).map(&:artist).uniq.sort_by(&:downcase)
    @artistcount = @artists.length/3
    @artists1 = @artists[0..(@artistcount-1)]
    @artists2 = @artists[(@artistcount)..(@artistcount*2-1)]
    @artists3 = @artists[(@artistcount*2)..(@artistcount*3-1)]
  end

  def show
    @artist = params[:id]
    @works = Place.where(artist:@artist)
    @name = @artist.split(",")
  end

end

app/controllers/farsearch_controller.rb
class FarsearchController < ApplicationController
  def index
  end

  def search
    @result = Place.near(params["query"], 10, :order => "distance").limit(10)
    @getresults = @result.length > 0
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
  end

  def search
  end

  def results
    @results = Location.near(params["query"], 10, :order => "distance").limit(10)
  end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController

  def index
    if request.xhr?
      render(json: Location.all)
    else
      redirect_to root_path
    end
  end

  def show
    if request.xhr?
      render(json: Location.find(params['markerid']))
    else
      redirect_to root_path
    end
  end


end

app/controllers/shownearby_controller.rb
class ShownearbyController < ApplicationController
  def index
  end

  def load
    @resulttrack = 0
    @@resultspage = 0
    @showprev = false
    @shownext = true
    @@allspots = Place.near([params['lat'], params['long']], 10, :order => "distance").limit(100)
    @nearbyspots = Place.near([params['lat'], params['long']], 10, :order => "distance").limit(100)[@@resultspage..@@resultspage+9]
    render :json => {
      :partial => render_to_string(:partial => 'shownearby/map')
    }
  end

  def nextresults
    @@resultspage += 10
    @resulttrack = @@resultspage
    @showprev = @@resultspage > 0
    @shownext = @@resultspage < 90
    @nearbyspots = @@allspots[@@resultspage..@@resultspage+9]
    p @nearbyspots
    render :json => {
      :partial => render_to_string(:partial => 'shownearby/locations')
    }
  end

  def prevresults
    @@resultspage -= 10
    @resulttrack = @@resultspage
    @showprev = @@resultspage > 0
    @shownext = @@resultspage < 90
    @nearbyspots = @@allspots[@@resultspage..@@resultspage+9]
    p @nearbyspots
    render :json => {
      :partial => render_to_string(:partial => 'shownearby/locations')
    }
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artistsearch_helper.rb
module ArtistsearchHelper
end

app/helpers/locationsearch_helper.rb
module LocationsearchHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/helpers/nearbysearch_helper.rb
module NearbysearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SF Open Art</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js"></script>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCE-897CDl9CnFtZDVIQEQkd409ibKqcmQ" type="text/javascript"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-regular" id="headline">
          <%= link_to image_tag('artlogo.png', id: 'logo'), root_path %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class='menuitem'><%=link_to 'Show Nearby Art', nearbylocations_path %></li>
          <li class='menuitem'><%=link_to 'Search by Location', locations_search_path %></li>
          <li class='menuitem'><%=link_to 'Search by Artist', artists_path %></li>
          <li class='menuitem'><%=link_to 'Show Full Map', locations_path %></li>
          <li class='menuitem'><%=link_to 'About', about_path %></li>
        </ul>
      </div>
    </div>
  </nav>
<div id="main">
  <%= yield %>
</div>
</body>
</html>